### PR TITLE
[sentry_lumberdash] Support latest sentry version and add tests

### PR DESCRIPTION
**Pull request by ueman**
This PR updates sentry_lumberdash to the latest Sentry version.
I also added tests and it should now have complete coverage.
I've also improved the documentation and various links.

### CODE REVIEW

**Comment by ueman** [comment]
I'm not quite sure why this decreases the coverage. I just updated dependencies and didn't change any code.
Let me know if there's anything left to do.

**Comment by ueman** [comment]
Docker pull failed but the build should be green if you restart it. Instead of docker you could also use the GitHub Dart Action: https://github.com/dart-lang/setup-dart

**Comment by ueman** [comment]
@fabiomcarneiro or @fwagner do you mind taking a look at this?

**Review by fabiomcarneiro — APPROVED** [review]
LGTM . Thank you.

**Review by fwagner — APPROVED** [review]

**Comment by fwagner** [comment]
Thanks @ueman. New version is available on pub.dev: https://pub.dev/packages/sentry_lumberdash/versions/3.1.0.

**Pull request merged**
